services:
#  app:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: spribedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  test-db:
    image: postgres:16
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"

volumes:
  postgres_data:
